### ISSUE TITLE
Terrain reversion

### ISSUE THREAD

**Issue by Drudicta** [zambony/Gungnir#34]
**What version of Gungnir were you using?** 1.6.0

**What happened?** Terrain went back to damaged

**What command or feature were you using at the time?** /treset 5

**Replication Procedure:** Place down a campfire after a single pickaxe, wait for it to burn out, rebury with /treset. Also still happens if you remove the campfire later to try and reset anyway. This is done on my Fiance's local server.

**Screenshots or Logs:** I should have though of getting this as the problem happened....

**Comment by zambony** [comment]
Does this happen even in singleplayer?

**Comment by zambony** [comment]
I haven't been able to replicate this so far. I'll keep it open for a bit, in case I have any success.

**Comment by adrian-wong** [comment]
I've been able to replicate this issue, only in multiplayer.  This is most likely due to how the current version of Valheim handles terrian modification saved states.

If i use the command near another player, on my screen it'll appear to work, but once i leave the area and return, the state of the area will be as if I did not execute the command.

**Comment by zambony** [comment]
That's helpful to know, it sounds like the players haven't agreed on the terrain reversion, and other clients are reverting it. I'll find a way to synchronize it with everyone online.

**Comment by Drudicta** [comment]
> Does this happen even in singleplayer?

Sorry for some reason this all went to Junkmail. It does not happen off of servers, but it will happen even I'm the host of a server.
